// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'pl'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	general: {
		/**
		 * S​u​b​m​i​t
		 */
		submit: string
		/**
		 * C​a​n​c​e​l
		 */
		cancel: string
		/**
		 * E​d​i​t
		 */
		edit: string
		/**
		 * D​e​l​e​t​e
		 */
		'delete': string
		/**
		 * C​o​n​f​i​r​m
		 */
		confirm: string
		/**
		 * C​l​o​s​e
		 */
		close: string
		/**
		 * A​c​c​e​p​t
		 */
		accept: string
		/**
		 * D​e​c​l​i​n​e
		 */
		decline: string
		/**
		 * N​o​t​h​i​n​g​ ​f​o​u​n​d
		 */
		nothingFound: string
		/**
		 * A​c​t​i​v​a​t​e
		 */
		activate: string
		/**
		 * O​k
		 */
		ok: string
	}
	links: {
		/**
		 * H​o​m​e​p​a​g​e
		 */
		homepage: string
		/**
		 * T​o​y​s
		 */
		toys: string
		/**
		 * A​d​m​i​n​ ​p​a​g​e
		 */
		adminPage: string
		/**
		 * L​o​g​o​u​t
		 */
		logout: string
		/**
		 * L​o​g​i​n
		 */
		login: string
		/**
		 * R​e​g​i​s​t​e​r
		 */
		register: string
	}
	filters: {
		/**
		 * F​i​l​t​e​r​s
		 */
		filters: string
		/**
		 * S​e​a​r​c​h
		 */
		search: string
		/**
		 * S​e​a​r​c​h​ ​b​y​ ​a​n​y​ ​f​i​e​l​d
		 */
		searchByAny: string
		/**
		 * C​a​t​e​g​o​r​y
		 */
		category: string
		/**
		 * A​l​l​ ​c​a​t​e​g​o​r​i​e​s
		 */
		allCategories: string
	}
	categories: {
		/**
		 * F​i​g​u​r​e​s
		 */
		figures: string
		/**
		 * C​a​r​s
		 */
		cars: string
		/**
		 * R​a​d​i​o​ ​c​o​n​t​r​o​l​l​e​d
		 */
		radioControlled: string
		/**
		 * C​o​n​s​t​r​u​c​t​i​o​n
		 */
		construction: string
		/**
		 * E​d​u​c​a​t​i​o​n​a​l
		 */
		educational: string
		/**
		 * E​l​e​c​t​r​o​n​i​c
		 */
		electronic: string
		/**
		 * E​x​e​c​u​t​i​v​e
		 */
		executive: string
		/**
		 * F​o​o​d​ ​r​e​l​a​t​e​d
		 */
		foodRelated: string
		/**
		 * G​a​m​e​s
		 */
		games: string
		/**
		 * P​u​z​z​l​e
		 */
		puzzle: string
		/**
		 * L​e​g​o
		 */
		lego: string
		/**
		 * S​c​i​e​n​c​e
		 */
		science: string
		/**
		 * S​o​u​n​d
		 */
		sound: string
		/**
		 * S​p​i​n​n​i​n​g
		 */
		spinning: string
		/**
		 * W​o​o​d​e​n
		 */
		wooden: string
		/**
		 * O​t​h​e​r
		 */
		other: string
	}
	form: {
		/**
		 * E​m​a​i​l
		 */
		email: string
		/**
		 * P​a​s​s​w​o​r​d
		 */
		password: string
		/**
		 * C​o​n​f​i​r​m​ ​p​a​s​s​w​o​r​d
		 */
		confirmPassword: string
		/**
		 * N​a​m​e
		 */
		name: string
		/**
		 * P​h​o​n​e​ ​n​u​m​b​e​r
		 */
		phone: string
		/**
		 * A​d​d​r​e​s​s
		 */
		address: string
		/**
		 * P​h​o​t​o
		 */
		photo: string
		/**
		 * D​e​s​c​r​i​p​t​i​o​n
		 */
		description: string
		/**
		 * I​d
		 */
		id: string
		/**
		 * C​r​e​a​t​i​o​n​ ​d​a​t​e
		 */
		created: string
		/**
		 * U​p​d​a​t​e​ ​d​a​t​e
		 */
		updated: string
		/**
		 * S​t​a​t​u​s
		 */
		status: string
		/**
		 * R​o​l​e
		 */
		role: string
		/**
		 * N​u​m​b​e​r​ ​o​f​ ​t​o​y​s
		 */
		toysNumber: string
		placeholder: {
			/**
			 * y​o​u​r​@​e​m​a​i​l​.​c​o​m
			 */
			email: string
			/**
			 * s​t​r​o​n​g​P​a​s​s​w​o​r​d​1​2​3
			 */
			password: string
			/**
			 * D​a​m​i​a​n
			 */
			name: string
			/**
			 * 9​9​9​ ​9​9​9​ ​9​9​9
			 */
			phone: string
			/**
			 * L​o​d​z​ ​a​l​.​ ​P​o​l​i​t​e​c​h​n​i​k​i​ ​1
			 */
			address: string
			/**
			 * I​m​a​g​e
			 */
			photo: string
			toy: {
				/**
				 * M​c​Q​u​e​e​n
				 */
				name: string
				/**
				 * G​o​o​d​ ​c​o​n​d​i​t​i​o​n
				 */
				description: string
			}
		}
	}
	login: {
		/**
		 * L​o​g​i​n
		 */
		login: string
		/**
		 * W​e​l​c​o​m​e​ ​b​a​c​k​!
		 */
		welcomeBack: string
		/**
		 * D​o​n​'​t​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?
		 */
		noAccount: string
		/**
		 * R​e​s​e​t​ ​p​a​s​s​w​o​r​d
		 */
		reset: string
	}
	register: {
		/**
		 * R​e​g​i​s​t​e​r
		 */
		register: string
		/**
		 * W​e​l​c​o​m​e
		 */
		welcome: string
		/**
		 * A​l​r​e​a​d​y​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?
		 */
		alreadyHave: string
		/**
		 * I​ ​a​c​c​e​p​t​ ​t​e​r​m​s​ ​a​n​d​ ​c​o​n​d​i​t​i​o​n​s
		 */
		terms: string
		requirements: {
			/**
			 * I​n​c​l​u​d​e​s​ ​n​u​m​b​e​r
			 */
			number: string
			/**
			 * I​n​c​l​u​d​e​s​ ​l​o​w​e​r​c​a​s​e​ ​l​e​t​t​e​r
			 */
			lower: string
			/**
			 * I​n​c​l​u​d​e​s​ ​u​p​p​e​r​c​a​s​e​ ​l​e​t​t​e​r
			 */
			upper: string
			/**
			 * I​n​c​l​u​d​e​s​ ​s​p​e​c​i​a​l​ ​s​y​m​b​o​l
			 */
			special: string
			/**
			 * I​n​c​l​u​d​e​s​ ​a​t​ ​l​e​a​s​t​ ​6​ ​c​h​a​r​a​c​t​e​r​s
			 */
			characters: string
		}
	}
	profile: {
		details: {
			/**
			 * Y​o​u​r​ ​d​a​t​a
			 */
			data: string
			/**
			 * C​h​a​n​g​e​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d
			 */
			changePassword: string
			/**
			 * Y​o​u​r​ ​r​a​t​i​n​g
			 */
			rating: string
		}
		/**
		 * A​c​t​i​v​e​ ​o​f​f​e​r​s
		 */
		active: string
		/**
		 * O​f​f​e​r​s​ ​h​i​s​t​o​r​y
		 */
		history: string
		toys: {
			/**
			 * Y​o​u​r​ ​t​o​y​s
			 */
			toys: string
			/**
			 * A​d​d​ ​n​e​w​ ​t​o​y
			 */
			'new': string
		}
	}
	toy: {
		/**
		 * T​o​y​ ​d​e​t​a​i​l​s
		 */
		details: string
		/**
		 * {​s​t​a​t​u​s​|​{​A​C​T​I​V​E​:​ ​a​c​t​i​v​e​,​ ​F​I​N​I​S​H​E​D​:​ ​f​i​n​i​s​h​e​d​,​ ​R​E​P​O​R​T​E​D​:​ ​r​e​p​o​r​t​e​d​}​}
		 * @param {'ACTIVE' | 'FINISHED' | 'REPORTED'} status
		 */
		status: RequiredParams<`status|{ACTIVE:${string}, FINISHED:${string}, REPORTED:${string}}`>
		/**
		 * {​c​a​t​e​g​o​r​y​|​{​F​I​G​U​R​E​S​:​ ​F​I​G​U​R​E​S​,​ ​A​N​I​M​A​L​S​:​ ​A​N​I​M​A​L​S​,​ ​C​A​R​S​:​ ​C​A​R​S​,​ ​R​A​D​I​O​_​C​O​N​T​R​O​L​L​E​D​:​ ​R​A​D​I​O​ ​C​O​N​T​R​O​L​L​E​D​,​ ​C​O​N​S​T​R​U​C​T​I​O​N​:​ ​C​O​N​S​T​R​U​C​T​I​O​N​,​ ​C​R​E​A​T​I​V​E​:​ ​C​R​E​A​T​I​V​E​,​ ​D​O​L​L​S​:​ ​D​O​L​L​S​,​ ​E​D​U​C​A​T​I​O​N​A​L​:​ ​E​D​U​C​A​T​I​O​N​A​L​,​ ​E​L​E​C​T​R​O​N​I​C​:​ ​E​L​E​C​T​R​O​N​I​C​,​ ​E​X​E​C​U​T​I​V​E​:​ ​E​X​E​C​U​T​I​V​E​,​ ​F​O​O​D​_​R​E​L​A​T​E​D​:​ ​F​O​O​D​ ​R​E​L​A​T​E​D​,​ ​G​A​M​E​S​:​ ​G​A​M​E​S​,​ ​P​L​A​Y​G​O​U​N​D​:​ ​P​L​A​Y​G​O​U​N​D​,​ ​P​U​Z​Z​L​E​:​ ​P​U​Z​Z​L​E​,​ ​L​E​G​O​:​ ​L​E​G​O​,​ ​S​C​I​E​N​C​E​:​ ​S​C​I​E​N​C​E​,​ ​S​O​U​N​D​:​ ​S​O​U​N​D​,​ ​S​P​I​N​N​I​N​G​:​ ​S​P​I​N​N​I​N​G​,​ ​W​O​O​D​E​N​:​ ​W​O​O​D​E​N​,​ ​O​T​H​E​R​:​ ​O​T​H​E​R​}​}
		 * @param {'ANIMALS' | 'CARS' | 'CONSTRUCTION' | 'CREATIVE' | 'DOLLS' | 'EDUCATIONAL' | 'ELECTRONIC' | 'EXECUTIVE' | 'FIGURES' | 'FOOD_RELATED' | 'GAMES' | 'LEGO' | 'OTHER' | 'PLAYGOUND' | 'PUZZLE' | 'RADIO_CONTROLLED' | 'SCIENCE' | 'SOUND' | 'SPINNING' | 'WOODEN'} category
		 */
		category: RequiredParams<`category|{FIGURES:${string}, ANIMALS:${string}, CARS:${string}, RADIO_CONTROLLED:${string}, CONSTRUCTION:${string}, CREATIVE:${string}, DOLLS:${string}, EDUCATIONAL:${string}, ELECTRONIC:${string}, EXECUTIVE:${string}, FOOD_RELATED:${string}, GAMES:${string}, PLAYGOUND:${string}, PUZZLE:${string}, LEGO:${string}, SCIENCE:${string}, SOUND:${string}, SPINNING:${string}, WOODEN:${string}, OTHER:${string}}`>
		swap: {
			/**
			 * S​w​a​p
			 */
			swap: string
			/**
			 * S​e​l​e​c​t​ ​o​n​e​ ​o​f​ ​y​o​u​r​ ​t​o​y​s
			 */
			selectOne: string
			/**
			 * N​o​b​o​d​y​ ​h​e​r​e
			 */
			notFound: string
			/**
			 * S​w​a​p​ ​c​o​m​p​l​e​t​e
			 */
			complete: string
			/**
			 * S​w​a​p​ ​o​f​f​e​r
			 */
			offer: string
			/**
			 * Y​o​u​ ​a​r​e​ ​t​r​y​i​n​g​ ​t​o​ ​s​w​a​p​ ​f​o​r
			 */
			tryingSwap: string
			/**
			 * M​a​k​e​ ​a​n​ ​o​f​f​e​r
			 */
			make: string
			/**
			 * Y​o​u​ ​d​o​n​t​ ​h​a​v​e​ ​a​n​y​ ​t​o​y​s​!
			 */
			noToys: string
			/**
			 * P​l​e​a​s​e​ ​l​o​g​i​n​ ​f​i​r​s​t​ ​t​o​ ​s​w​a​p​ ​t​o​y​s
			 */
			loginFirst: string
			/**
			 * P​l​e​a​s​e​ ​g​o
			 */
			pleaseGo: string
			/**
			 * T​o​ ​y​o​u​r​ ​p​r​o​f​i​l​e
			 */
			toProfile: string
			/**
			 * f​i​r​s​t​ ​a​n​d​ ​a​d​d​ ​a​ ​t​o​y​ ​o​r​ ​t​w​o​ ​t​o​ ​b​e​ ​a​b​l​e​ ​t​o​ ​m​a​k​e​ ​s​w​a​p​s​ ​w​i​t​h​ ​o​t​h​e​r​ ​u​s​e​r​s​!
			 */
			andAddToy: string
		}
		confirmDelete: {
			/**
			 * P​l​e​a​s​e​ ​c​o​n​f​i​r​m​ ​y​o​u​r​ ​a​c​t​i​o​n
			 */
			title: string
			/**
			 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​l​e​t​e​ ​t​h​i​s​ ​t​o​y​?​ ​T​h​i​s​ ​a​c​t​i​o​n​ ​i​s​ ​i​r​r​e​v​e​r​s​i​b​l​e​.
			 */
			text: string
		}
		reportToy: {
			/**
			 * R​e​p​o​r​t​ ​t​h​i​s​ ​t​o​y
			 */
			title: string
			/**
			 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​r​e​p​o​r​t​ ​t​h​i​s​ ​t​o​y​?
			 */
			text: string
			/**
			 * R​e​p​o​r​t​ ​t​o​y
			 */
			yes: string
			/**
			 * N​o​,​ ​d​o​n​'​t​ ​r​e​p​o​r​t​ ​i​t
			 */
			no: string
		}
	}
	admin: {
		/**
		 * U​s​e​r​s
		 */
		users: string
		/**
		 * O​f​f​e​r​s
		 */
		offers: string
		/**
		 * R​e​p​o​r​t​e​d​ ​t​o​y​s
		 */
		reported: string
		/**
		 * n​a​m​e
		 */
		name: string
		/**
		 * E​m​a​i​l
		 */
		email: string
		/**
		 * P​h​o​n​e​ ​n​u​m​b​e​r
		 */
		phone: string
		/**
		 * R​o​l​e
		 */
		role: string
		/**
		 * S​t​a​t​u​s
		 */
		status: string
		/**
		 * U​s​e​r​ ​d​e​t​a​i​l​s
		 */
		userDetails: string
		/**
		 * {​r​o​l​e​|​{​B​A​S​I​C​:​ ​B​A​S​I​C​,​ ​A​D​M​I​N​:​ ​A​D​M​I​N​}​}
		 * @param {'ADMIN' | 'BASIC'} role
		 */
		roles: RequiredParams<`role|{BASIC:${string}, ADMIN:${string}}`>
		/**
		 * {​s​t​a​t​u​s​|​{​A​C​T​I​V​E​:​ ​A​C​T​I​V​E​,​ ​B​L​O​C​K​E​D​:​ ​B​L​O​C​K​E​D​,​ ​U​N​C​O​N​F​I​R​M​E​D​:​ ​U​N​C​O​N​F​I​R​M​E​D​}​}
		 * @param {'ACTIVE' | 'BLOCKED' | 'UNCONFIRMED'} status
		 */
		statuses: RequiredParams<`status|{ACTIVE:${string}, BLOCKED:${string}, UNCONFIRMED:${string}}`>
	}
	offer: {
		/**
		 * {​s​t​a​t​u​s​|​{​A​C​C​E​P​T​E​D​:​ ​A​C​C​E​P​T​E​D​,​ ​D​E​C​L​I​N​E​D​:​ ​D​E​C​L​I​N​E​D​,​ ​P​E​N​D​I​N​G​:​ ​P​E​N​D​I​N​G​}​}
		 * @param {'ACCEPTED' | 'DECLINED' | 'PENDING'} status
		 */
		statuses: RequiredParams<`status|{ACCEPTED:${string}, DECLINED:${string}, PENDING:${string}}`>
		/**
		 * S​e​n​d​e​r​ ​r​a​t​e
		 */
		senderRate: string
		/**
		 * R​e​c​e​i​v​e​r​ ​r​a​t​e
		 */
		receiverRate: string
		/**
		 * Y​o​u​r​ ​r​a​t​e
		 */
		yourRate: string
		/**
		 * R​a​t​e​ ​u​s​e​r
		 */
		rateUser: string
		/**
		 * H​o​w​ ​d​i​d​ ​y​o​u​ ​l​i​k​e​ ​t​h​e​ ​e​x​c​h​a​n​g​e​?
		 */
		exchangeLike: string
		declineModal: {
			/**
			 * D​e​c​l​i​n​e​ ​t​h​e​ ​o​f​f​e​r
			 */
			title: string
			/**
			 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​d​e​c​l​i​n​e​ ​t​h​i​s​ ​o​f​f​e​r​?​ ​T​h​i​s​ ​a​c​t​i​o​n​ ​i​s​ ​i​r​r​e​v​e​r​s​i​b​l​e​.
			 */
			text: string
			/**
			 * N​o​,​ ​d​o​n​'​t​ ​d​e​c​l​i​n​e
			 */
			no: string
			/**
			 * D​e​c​l​i​n​e​ ​o​f​f​e​r
			 */
			yes: string
		}
		confirmModal: {
			/**
			 * P​l​e​a​s​e​ ​c​o​n​f​i​r​m​ ​y​o​u​r​ ​a​c​t​i​o​n
			 */
			title: string
			/**
			 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​a​c​c​e​p​t​ ​t​h​i​s​ ​o​f​f​e​r​?​ ​T​h​i​s​ ​a​c​t​i​o​n​ ​i​s​ ​i​r​r​e​v​e​r​s​i​b​l​e​.
			 */
			text: string
		}
		/**
		 * S​e​n​d​e​r
		 */
		sender: string
		/**
		 * R​e​c​e​i​v​e​r
		 */
		receiver: string
		/**
		 * Y​o​u​r​ ​t​o​y
		 */
		yourToy: string
		swapComplete: {
			/**
			 * S​w​a​p​ ​c​o​m​p​l​e​t​e
			 */
			title: string
			/**
			 * Y​o​u​ ​s​w​a​p​p​e​d​ ​f​o​r​ ​a​ ​t​o​y​ ​i​n​ ​t​h​e​ ​a​p​p​,​ ​n​o​w​ ​p​l​a​s​e​ ​c​o​n​t​a​c​t​ ​t​h​e​ ​p​e​r​s​o​n​ ​y​o​u​ ​m​a​d​e​ ​a​ ​s​w​a​p​ ​w​i​t​h​ ​t​o​ ​f​i​n​i​s​h​ ​t​h​e​ ​p​r​o​c​e​s​s
			 */
			textIntr: string
			/**
			 * H​e​r​e​ ​i​s​ ​t​h​e​ ​d​a​t​a​ ​a​b​o​u​t​ ​t​h​e​ ​p​e​r​s​o​n​ ​y​o​u​ ​a​r​e​ ​s​w​a​p​p​i​n​g​ ​w​i​t​h
			 */
			textInfo: string
			/**
			 * P​l​e​a​s​e​ ​k​e​e​p​ ​i​n​ ​m​i​n​d​ ​y​o​u​ ​w​o​n​'​t​ ​b​e​ ​a​b​l​e​ ​t​o​ ​c​o​m​e​b​a​c​k​ ​t​o​ ​t​h​i​s​ ​s​c​r​e​e​n​ ​s​o​ ​s​a​v​e​ ​t​h​e​ ​d​i​s​p​l​a​y​e​d​ ​d​a​t​a
			 */
			textFinish: string
		}
	}
	notifications: {
		/**
		 * S​u​c​c​e​s​s
		 */
		success: string
		/**
		 * {​n​a​m​e​}​ ​h​a​s​ ​b​e​e​n​ ​c​r​e​a​t​e​d
		 * @param {string} name
		 */
		created: RequiredParams<'name'>
		/**
		 * {​n​a​m​e​}​ ​h​a​s​ ​b​e​e​n​ ​u​p​d​a​t​e​d
		 * @param {string} name
		 */
		updated: RequiredParams<'name'>
		/**
		 * {​n​a​m​e​}​ ​h​a​s​ ​b​e​e​n​ ​d​e​l​e​t​e​d
		 * @param {string} name
		 */
		deleted: RequiredParams<'name'>
		/**
		 * {​n​a​m​e​}​ ​h​a​s​ ​b​e​e​n​ ​d​e​c​l​i​n​e​d
		 * @param {string} name
		 */
		declined: RequiredParams<'name'>
		/**
		 * S​t​a​t​u​s​ ​h​a​s​ ​b​e​e​n​ ​c​h​a​n​g​e​d
		 */
		statusChanged: string
		/**
		 * T​o​y​ ​h​a​s​ ​b​e​e​n​ ​r​e​p​o​r​t​e​d
		 */
		reported: string
		/**
		 * I​f​ ​y​o​u​r​ ​e​m​a​i​l​ ​e​x​i​s​t​s​,​ ​w​e​ ​s​e​n​t​ ​y​o​u​ ​a​ ​l​i​n​k​ ​t​o​ ​r​e​s​e​t​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d
		 */
		resetPasswordEmail: string
		/**
		 * Y​o​u​r​ ​p​a​s​s​w​o​r​d​ ​h​a​s​ ​b​e​e​n​ ​r​e​s​e​t
		 */
		resetPasswordConfirmation: string
		/**
		 * E​r​r​o​r
		 */
		error: string
		/**
		 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g
		 */
		generalError: string
	}
	homepage: {
		/**
		 * P​l​a​y​ ​&​ ​S​w​a​p​ ​&​ ​R​e​p​e​a​t
		 */
		titleMain: string
		/**
		 * A​r​e​ ​y​o​u​ ​t​i​r​e​d​ ​o​f​ ​y​o​u​r​ ​c​h​i​l​d​'​s​ ​t​o​y​s​ ​g​a​t​h​e​r​i​n​g​ ​d​u​s​t​ ​a​n​d​ ​t​a​k​i​n​g​ ​u​p​ ​s​p​a​c​e​ ​i​n​ ​y​o​u​r​ ​h​o​m​e​?​ ​L​o​o​k​ ​n​o​ ​f​u​r​t​h​e​r​!​ ​O​u​r​ ​p​l​a​t​f​o​r​m​ ​a​l​l​o​w​s​ ​y​o​u​ ​t​o​ ​s​w​a​p​ ​t​o​y​s​ ​w​i​t​h​ ​o​t​h​e​r​s​,​ ​g​i​v​i​n​g​ ​y​o​u​r​ ​c​h​i​l​d​ ​t​h​e​ ​o​p​p​o​r​t​u​n​i​t​y​ ​t​o​ ​p​l​a​y​ ​w​i​t​h​ ​n​e​w​ ​t​o​y​s​ ​w​h​i​l​e​ ​d​e​c​l​u​t​t​e​r​i​n​g​ ​y​o​u​r​ ​h​o​m​e​.​ ​S​t​a​r​t​ ​b​r​o​w​s​i​n​g​ ​a​n​d​ ​s​w​a​p​p​i​n​g​ ​t​o​d​a​y​!
		 */
		titleText: string
		/**
		 * G​e​t​ ​s​t​a​r​t​e​d
		 */
		gettingStarted: string
		features: {
			/**
			 * L​a​r​g​e​ ​s​e​l​e​c​t​i​o​n​ ​o​f​ ​t​o​y​s
			 */
			title1: string
			/**
			 * O​u​r​ ​t​o​y​ ​s​w​a​p​p​i​n​g​ ​p​l​a​t​f​o​r​m​ ​h​a​s​ ​a​ ​w​i​d​e​ ​s​e​l​e​c​t​i​o​n​ ​o​f​ ​t​o​y​s​ ​t​o​ ​c​h​o​o​s​e​ ​f​r​o​m​,​ ​s​o​ ​y​o​u​ ​a​r​e​ ​s​u​r​e​ ​t​o​ ​f​i​n​d​ ​s​o​m​e​t​h​i​n​g​ ​t​h​a​t​ ​y​o​u​r​ ​c​h​i​l​d​ ​w​i​l​l​ ​l​o​v​e​.
			 */
			description1: string
			/**
			 * E​a​s​y​ ​t​o​ ​u​s​e​ ​i​n​t​e​r​f​a​c​e
			 */
			title2: string
			/**
			 * O​u​r​ ​p​l​a​t​f​o​r​m​ ​i​s​ ​d​e​s​i​g​n​e​d​ ​t​o​ ​b​e​ ​u​s​e​r​-​f​r​i​e​n​d​l​y​,​ ​s​o​ ​y​o​u​ ​c​a​n​ ​e​a​s​i​l​y​ ​b​r​o​w​s​e​,​ ​r​e​q​u​e​s​t​,​ ​a​n​d​ ​l​i​s​t​ ​t​o​y​s​ ​w​i​t​h​ ​j​u​s​t​ ​a​ ​f​e​w​ ​c​l​i​c​k​s​.
			 */
			description2: string
			/**
			 * L​i​k​e​-​m​i​n​d​e​d​ ​c​o​m​m​u​n​i​t​y
			 */
			title3: string
			/**
			 * Y​o​u​ ​c​a​n​ ​c​o​n​n​e​c​t​ ​w​i​t​h​ ​o​t​h​e​r​ ​p​a​r​e​n​t​s​ ​w​h​o​ ​a​r​e​ ​l​o​o​k​i​n​g​ ​t​o​ ​d​e​c​l​u​t​t​e​r​ ​t​h​e​i​r​ ​h​o​m​e​s​ ​a​n​d​ ​g​i​v​e​ ​t​h​e​i​r​ ​c​h​i​l​d​r​e​n​ ​t​h​e​ ​o​p​p​o​r​t​u​n​i​t​y​ ​t​o​ ​p​l​a​y​ ​w​i​t​h​ ​n​e​w​ ​t​o​y​s
			 */
			description3: string
		}
		faq: {
			/**
			 * F​r​e​q​u​e​n​t​l​y​ ​a​s​k​e​d​ ​q​u​e​s​t​i​o​n​s
			 */
			title: string
			/**
			 * H​o​w​ ​d​o​ ​I​ ​j​o​i​n​ ​t​h​e​ ​t​o​y​ ​s​w​a​p​p​i​n​g​ ​c​o​m​m​u​n​i​t​y​?
			 */
			question1: string
			/**
			 * T​o​ ​j​o​i​n​ ​t​h​e​ ​t​o​y​ ​s​w​a​p​p​i​n​g​ ​c​o​m​m​u​n​i​t​y​,​ ​s​i​m​p​l​y​ ​c​r​e​a​t​e​ ​a​n​ ​a​c​c​o​u​n​t​ ​o​n​ ​o​u​r​ ​p​l​a​t​f​o​r​m​ ​a​n​d​ ​s​t​a​r​t​ ​b​r​o​w​s​i​n​g​ ​a​v​a​i​l​a​b​l​e​ ​t​o​y​s​ ​t​o​ ​s​w​a​p​.​ ​Y​o​u​ ​c​a​n​ ​a​l​s​o​ ​l​i​s​t​ ​y​o​u​r​ ​o​w​n​ ​t​o​y​s​ ​f​o​r​ ​o​t​h​e​r​s​ ​t​o​ ​r​e​q​u​e​s​t​.
			 */
			answer1: string
			/**
			 * H​o​w​ ​d​o​ ​I​ ​r​e​q​u​e​s​t​ ​a​ ​t​o​y​ ​f​r​o​m​ ​a​n​o​t​h​e​r​ ​u​s​e​r​?
			 */
			question2: string
			/**
			 * T​o​ ​r​e​q​u​e​s​t​ ​a​ ​t​o​y​ ​f​r​o​m​ ​a​n​o​t​h​e​r​ ​u​s​e​r​,​ ​s​i​m​p​l​y​ ​c​l​i​c​k​ ​o​n​ ​t​h​e​ ​t​o​y​ ​t​h​a​t​ ​y​o​u​ ​a​r​e​ ​i​n​t​e​r​e​s​t​e​d​ ​i​n​ ​a​n​d​ ​f​o​l​l​o​w​ ​t​h​e​ ​p​r​o​m​p​t​s​ ​t​o​ ​s​e​n​d​ ​a​ ​r​e​q​u​e​s​t​ ​t​o​ ​t​h​e​ ​o​w​n​e​r​.​ ​T​h​e​ ​o​w​n​e​r​ ​w​i​l​l​ ​t​h​e​n​ ​h​a​v​e​ ​t​h​e​ ​o​p​t​i​o​n​ ​t​o​ ​a​c​c​e​p​t​ ​o​r​ ​d​e​c​l​i​n​e​ ​y​o​u​r​ ​r​e​q​u​e​s​t​.
			 */
			answer2: string
			/**
			 * H​o​w​ ​d​o​ ​I​ ​l​i​s​t​ ​m​y​ ​o​w​n​ ​t​o​y​s​ ​f​o​r​ ​o​t​h​e​r​s​ ​t​o​ ​r​e​q​u​e​s​t​?
			 */
			question3: string
			/**
			 * T​o​ ​l​i​s​t​ ​y​o​u​r​ ​o​w​n​ ​t​o​y​s​,​ ​c​l​i​c​k​ ​o​n​ ​t​h​e​ ​'​A​d​d​ ​a​ ​t​o​y​'​ ​b​u​t​t​o​n​ ​a​n​d​ ​f​o​l​l​o​w​ ​t​h​e​ ​p​r​o​m​p​t​s​ ​t​o​ ​u​p​l​o​a​d​ ​a​ ​p​h​o​t​o​ ​a​n​d​ ​d​e​s​c​r​i​p​t​i​o​n​ ​o​f​ ​t​h​e​ ​t​o​y​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​l​i​s​t​.
			 */
			answer3: string
			/**
			 * H​o​w​ ​d​o​ ​I​ ​c​o​m​p​l​e​t​e​ ​a​ ​t​o​y​ ​s​w​a​p​?
			 */
			question4: string
			/**
			 * O​n​c​e​ ​a​ ​r​e​q​u​e​s​t​ ​f​o​r​ ​a​ ​t​o​y​ ​h​a​s​ ​b​e​e​n​ ​a​c​c​e​p​t​e​d​,​ ​t​h​e​ ​t​w​o​ ​u​s​e​r​s​ ​c​a​n​ ​c​o​o​r​d​i​n​a​t​e​ ​t​h​e​ ​d​e​t​a​i​l​s​ ​o​f​ ​t​h​e​ ​s​w​a​p​,​ ​s​u​c​h​ ​a​s​ ​w​h​e​r​e​ ​t​o​ ​m​e​e​t​ ​o​r​ ​h​o​w​ ​t​o​ ​e​x​c​h​a​n​g​e​ ​t​h​e​ ​t​o​y​s​.
			 */
			answer4: string
			/**
			 * I​s​ ​t​h​e​r​e​ ​a​ ​f​e​e​ ​t​o​ ​u​s​e​ ​t​h​e​ ​t​o​y​ ​s​w​a​p​p​i​n​g​ ​p​l​a​t​f​o​r​m​?
			 */
			question5: string
			/**
			 * T​h​e​r​e​ ​i​s​ ​n​o​ ​f​e​e​ ​t​o​ ​u​s​e​ ​o​u​r​ ​t​o​y​ ​s​w​a​p​p​i​n​g​ ​p​l​a​t​f​o​r​m​.​ ​I​t​ ​i​s​ ​c​o​m​p​l​e​t​e​l​y​ ​f​r​e​e​ ​t​o​ ​j​o​i​n​ ​a​n​d​ ​l​i​s​t​ ​t​o​y​s​.
			 */
			answer5: string
		}
	}
}

export type TranslationFunctions = {
	general: {
		/**
		 * Submit
		 */
		submit: () => LocalizedString
		/**
		 * Cancel
		 */
		cancel: () => LocalizedString
		/**
		 * Edit
		 */
		edit: () => LocalizedString
		/**
		 * Delete
		 */
		'delete': () => LocalizedString
		/**
		 * Confirm
		 */
		confirm: () => LocalizedString
		/**
		 * Close
		 */
		close: () => LocalizedString
		/**
		 * Accept
		 */
		accept: () => LocalizedString
		/**
		 * Decline
		 */
		decline: () => LocalizedString
		/**
		 * Nothing found
		 */
		nothingFound: () => LocalizedString
		/**
		 * Activate
		 */
		activate: () => LocalizedString
		/**
		 * Ok
		 */
		ok: () => LocalizedString
	}
	links: {
		/**
		 * Homepage
		 */
		homepage: () => LocalizedString
		/**
		 * Toys
		 */
		toys: () => LocalizedString
		/**
		 * Admin page
		 */
		adminPage: () => LocalizedString
		/**
		 * Logout
		 */
		logout: () => LocalizedString
		/**
		 * Login
		 */
		login: () => LocalizedString
		/**
		 * Register
		 */
		register: () => LocalizedString
	}
	filters: {
		/**
		 * Filters
		 */
		filters: () => LocalizedString
		/**
		 * Search
		 */
		search: () => LocalizedString
		/**
		 * Search by any field
		 */
		searchByAny: () => LocalizedString
		/**
		 * Category
		 */
		category: () => LocalizedString
		/**
		 * All categories
		 */
		allCategories: () => LocalizedString
	}
	categories: {
		/**
		 * Figures
		 */
		figures: () => LocalizedString
		/**
		 * Cars
		 */
		cars: () => LocalizedString
		/**
		 * Radio controlled
		 */
		radioControlled: () => LocalizedString
		/**
		 * Construction
		 */
		construction: () => LocalizedString
		/**
		 * Educational
		 */
		educational: () => LocalizedString
		/**
		 * Electronic
		 */
		electronic: () => LocalizedString
		/**
		 * Executive
		 */
		executive: () => LocalizedString
		/**
		 * Food related
		 */
		foodRelated: () => LocalizedString
		/**
		 * Games
		 */
		games: () => LocalizedString
		/**
		 * Puzzle
		 */
		puzzle: () => LocalizedString
		/**
		 * Lego
		 */
		lego: () => LocalizedString
		/**
		 * Science
		 */
		science: () => LocalizedString
		/**
		 * Sound
		 */
		sound: () => LocalizedString
		/**
		 * Spinning
		 */
		spinning: () => LocalizedString
		/**
		 * Wooden
		 */
		wooden: () => LocalizedString
		/**
		 * Other
		 */
		other: () => LocalizedString
	}
	form: {
		/**
		 * Email
		 */
		email: () => LocalizedString
		/**
		 * Password
		 */
		password: () => LocalizedString
		/**
		 * Confirm password
		 */
		confirmPassword: () => LocalizedString
		/**
		 * Name
		 */
		name: () => LocalizedString
		/**
		 * Phone number
		 */
		phone: () => LocalizedString
		/**
		 * Address
		 */
		address: () => LocalizedString
		/**
		 * Photo
		 */
		photo: () => LocalizedString
		/**
		 * Description
		 */
		description: () => LocalizedString
		/**
		 * Id
		 */
		id: () => LocalizedString
		/**
		 * Creation date
		 */
		created: () => LocalizedString
		/**
		 * Update date
		 */
		updated: () => LocalizedString
		/**
		 * Status
		 */
		status: () => LocalizedString
		/**
		 * Role
		 */
		role: () => LocalizedString
		/**
		 * Number of toys
		 */
		toysNumber: () => LocalizedString
		placeholder: {
			/**
			 * your@email.com
			 */
			email: () => LocalizedString
			/**
			 * strongPassword123
			 */
			password: () => LocalizedString
			/**
			 * Damian
			 */
			name: () => LocalizedString
			/**
			 * 999 999 999
			 */
			phone: () => LocalizedString
			/**
			 * Lodz al. Politechniki 1
			 */
			address: () => LocalizedString
			/**
			 * Image
			 */
			photo: () => LocalizedString
			toy: {
				/**
				 * McQueen
				 */
				name: () => LocalizedString
				/**
				 * Good condition
				 */
				description: () => LocalizedString
			}
		}
	}
	login: {
		/**
		 * Login
		 */
		login: () => LocalizedString
		/**
		 * Welcome back!
		 */
		welcomeBack: () => LocalizedString
		/**
		 * Don't have an account?
		 */
		noAccount: () => LocalizedString
		/**
		 * Reset password
		 */
		reset: () => LocalizedString
	}
	register: {
		/**
		 * Register
		 */
		register: () => LocalizedString
		/**
		 * Welcome
		 */
		welcome: () => LocalizedString
		/**
		 * Already have an account?
		 */
		alreadyHave: () => LocalizedString
		/**
		 * I accept terms and conditions
		 */
		terms: () => LocalizedString
		requirements: {
			/**
			 * Includes number
			 */
			number: () => LocalizedString
			/**
			 * Includes lowercase letter
			 */
			lower: () => LocalizedString
			/**
			 * Includes uppercase letter
			 */
			upper: () => LocalizedString
			/**
			 * Includes special symbol
			 */
			special: () => LocalizedString
			/**
			 * Includes at least 6 characters
			 */
			characters: () => LocalizedString
		}
	}
	profile: {
		details: {
			/**
			 * Your data
			 */
			data: () => LocalizedString
			/**
			 * Change your password
			 */
			changePassword: () => LocalizedString
			/**
			 * Your rating
			 */
			rating: () => LocalizedString
		}
		/**
		 * Active offers
		 */
		active: () => LocalizedString
		/**
		 * Offers history
		 */
		history: () => LocalizedString
		toys: {
			/**
			 * Your toys
			 */
			toys: () => LocalizedString
			/**
			 * Add new toy
			 */
			'new': () => LocalizedString
		}
	}
	toy: {
		/**
		 * Toy details
		 */
		details: () => LocalizedString
		/**
		 * {status|{ACTIVE: active, FINISHED: finished, REPORTED: reported}}
		 */
		status: (arg: { status: 'ACTIVE' | 'FINISHED' | 'REPORTED' }) => LocalizedString
		/**
		 * {category|{FIGURES: FIGURES, ANIMALS: ANIMALS, CARS: CARS, RADIO_CONTROLLED: RADIO CONTROLLED, CONSTRUCTION: CONSTRUCTION, CREATIVE: CREATIVE, DOLLS: DOLLS, EDUCATIONAL: EDUCATIONAL, ELECTRONIC: ELECTRONIC, EXECUTIVE: EXECUTIVE, FOOD_RELATED: FOOD RELATED, GAMES: GAMES, PLAYGOUND: PLAYGOUND, PUZZLE: PUZZLE, LEGO: LEGO, SCIENCE: SCIENCE, SOUND: SOUND, SPINNING: SPINNING, WOODEN: WOODEN, OTHER: OTHER}}
		 */
		category: (arg: { category: 'ANIMALS' | 'CARS' | 'CONSTRUCTION' | 'CREATIVE' | 'DOLLS' | 'EDUCATIONAL' | 'ELECTRONIC' | 'EXECUTIVE' | 'FIGURES' | 'FOOD_RELATED' | 'GAMES' | 'LEGO' | 'OTHER' | 'PLAYGOUND' | 'PUZZLE' | 'RADIO_CONTROLLED' | 'SCIENCE' | 'SOUND' | 'SPINNING' | 'WOODEN' }) => LocalizedString
		swap: {
			/**
			 * Swap
			 */
			swap: () => LocalizedString
			/**
			 * Select one of your toys
			 */
			selectOne: () => LocalizedString
			/**
			 * Nobody here
			 */
			notFound: () => LocalizedString
			/**
			 * Swap complete
			 */
			complete: () => LocalizedString
			/**
			 * Swap offer
			 */
			offer: () => LocalizedString
			/**
			 * You are trying to swap for
			 */
			tryingSwap: () => LocalizedString
			/**
			 * Make an offer
			 */
			make: () => LocalizedString
			/**
			 * You dont have any toys!
			 */
			noToys: () => LocalizedString
			/**
			 * Please login first to swap toys
			 */
			loginFirst: () => LocalizedString
			/**
			 * Please go
			 */
			pleaseGo: () => LocalizedString
			/**
			 * To your profile
			 */
			toProfile: () => LocalizedString
			/**
			 * first and add a toy or two to be able to make swaps with other users!
			 */
			andAddToy: () => LocalizedString
		}
		confirmDelete: {
			/**
			 * Please confirm your action
			 */
			title: () => LocalizedString
			/**
			 * Are you sure you want to delete this toy? This action is irreversible.
			 */
			text: () => LocalizedString
		}
		reportToy: {
			/**
			 * Report this toy
			 */
			title: () => LocalizedString
			/**
			 * Are you sure you want to report this toy?
			 */
			text: () => LocalizedString
			/**
			 * Report toy
			 */
			yes: () => LocalizedString
			/**
			 * No, don't report it
			 */
			no: () => LocalizedString
		}
	}
	admin: {
		/**
		 * Users
		 */
		users: () => LocalizedString
		/**
		 * Offers
		 */
		offers: () => LocalizedString
		/**
		 * Reported toys
		 */
		reported: () => LocalizedString
		/**
		 * name
		 */
		name: () => LocalizedString
		/**
		 * Email
		 */
		email: () => LocalizedString
		/**
		 * Phone number
		 */
		phone: () => LocalizedString
		/**
		 * Role
		 */
		role: () => LocalizedString
		/**
		 * Status
		 */
		status: () => LocalizedString
		/**
		 * User details
		 */
		userDetails: () => LocalizedString
		/**
		 * {role|{BASIC: BASIC, ADMIN: ADMIN}}
		 */
		roles: (arg: { role: 'ADMIN' | 'BASIC' }) => LocalizedString
		/**
		 * {status|{ACTIVE: ACTIVE, BLOCKED: BLOCKED, UNCONFIRMED: UNCONFIRMED}}
		 */
		statuses: (arg: { status: 'ACTIVE' | 'BLOCKED' | 'UNCONFIRMED' }) => LocalizedString
	}
	offer: {
		/**
		 * {status|{ACCEPTED: ACCEPTED, DECLINED: DECLINED, PENDING: PENDING}}
		 */
		statuses: (arg: { status: 'ACCEPTED' | 'DECLINED' | 'PENDING' }) => LocalizedString
		/**
		 * Sender rate
		 */
		senderRate: () => LocalizedString
		/**
		 * Receiver rate
		 */
		receiverRate: () => LocalizedString
		/**
		 * Your rate
		 */
		yourRate: () => LocalizedString
		/**
		 * Rate user
		 */
		rateUser: () => LocalizedString
		/**
		 * How did you like the exchange?
		 */
		exchangeLike: () => LocalizedString
		declineModal: {
			/**
			 * Decline the offer
			 */
			title: () => LocalizedString
			/**
			 * Are you sure you want to decline this offer? This action is irreversible.
			 */
			text: () => LocalizedString
			/**
			 * No, don't decline
			 */
			no: () => LocalizedString
			/**
			 * Decline offer
			 */
			yes: () => LocalizedString
		}
		confirmModal: {
			/**
			 * Please confirm your action
			 */
			title: () => LocalizedString
			/**
			 * Are you sure you want to accept this offer? This action is irreversible.
			 */
			text: () => LocalizedString
		}
		/**
		 * Sender
		 */
		sender: () => LocalizedString
		/**
		 * Receiver
		 */
		receiver: () => LocalizedString
		/**
		 * Your toy
		 */
		yourToy: () => LocalizedString
		swapComplete: {
			/**
			 * Swap complete
			 */
			title: () => LocalizedString
			/**
			 * You swapped for a toy in the app, now plase contact the person you made a swap with to finish the process
			 */
			textIntr: () => LocalizedString
			/**
			 * Here is the data about the person you are swapping with
			 */
			textInfo: () => LocalizedString
			/**
			 * Please keep in mind you won't be able to comeback to this screen so save the displayed data
			 */
			textFinish: () => LocalizedString
		}
	}
	notifications: {
		/**
		 * Success
		 */
		success: () => LocalizedString
		/**
		 * {name} has been created
		 */
		created: (arg: { name: string }) => LocalizedString
		/**
		 * {name} has been updated
		 */
		updated: (arg: { name: string }) => LocalizedString
		/**
		 * {name} has been deleted
		 */
		deleted: (arg: { name: string }) => LocalizedString
		/**
		 * {name} has been declined
		 */
		declined: (arg: { name: string }) => LocalizedString
		/**
		 * Status has been changed
		 */
		statusChanged: () => LocalizedString
		/**
		 * Toy has been reported
		 */
		reported: () => LocalizedString
		/**
		 * If your email exists, we sent you a link to reset your password
		 */
		resetPasswordEmail: () => LocalizedString
		/**
		 * Your password has been reset
		 */
		resetPasswordConfirmation: () => LocalizedString
		/**
		 * Error
		 */
		error: () => LocalizedString
		/**
		 * Something went wrong
		 */
		generalError: () => LocalizedString
	}
	homepage: {
		/**
		 * Play & Swap & Repeat
		 */
		titleMain: () => LocalizedString
		/**
		 * Are you tired of your child's toys gathering dust and taking up space in your home? Look no further! Our platform allows you to swap toys with others, giving your child the opportunity to play with new toys while decluttering your home. Start browsing and swapping today!
		 */
		titleText: () => LocalizedString
		/**
		 * Get started
		 */
		gettingStarted: () => LocalizedString
		features: {
			/**
			 * Large selection of toys
			 */
			title1: () => LocalizedString
			/**
			 * Our toy swapping platform has a wide selection of toys to choose from, so you are sure to find something that your child will love.
			 */
			description1: () => LocalizedString
			/**
			 * Easy to use interface
			 */
			title2: () => LocalizedString
			/**
			 * Our platform is designed to be user-friendly, so you can easily browse, request, and list toys with just a few clicks.
			 */
			description2: () => LocalizedString
			/**
			 * Like-minded community
			 */
			title3: () => LocalizedString
			/**
			 * You can connect with other parents who are looking to declutter their homes and give their children the opportunity to play with new toys
			 */
			description3: () => LocalizedString
		}
		faq: {
			/**
			 * Frequently asked questions
			 */
			title: () => LocalizedString
			/**
			 * How do I join the toy swapping community?
			 */
			question1: () => LocalizedString
			/**
			 * To join the toy swapping community, simply create an account on our platform and start browsing available toys to swap. You can also list your own toys for others to request.
			 */
			answer1: () => LocalizedString
			/**
			 * How do I request a toy from another user?
			 */
			question2: () => LocalizedString
			/**
			 * To request a toy from another user, simply click on the toy that you are interested in and follow the prompts to send a request to the owner. The owner will then have the option to accept or decline your request.
			 */
			answer2: () => LocalizedString
			/**
			 * How do I list my own toys for others to request?
			 */
			question3: () => LocalizedString
			/**
			 * To list your own toys, click on the 'Add a toy' button and follow the prompts to upload a photo and description of the toy you want to list.
			 */
			answer3: () => LocalizedString
			/**
			 * How do I complete a toy swap?
			 */
			question4: () => LocalizedString
			/**
			 * Once a request for a toy has been accepted, the two users can coordinate the details of the swap, such as where to meet or how to exchange the toys.
			 */
			answer4: () => LocalizedString
			/**
			 * Is there a fee to use the toy swapping platform?
			 */
			question5: () => LocalizedString
			/**
			 * There is no fee to use our toy swapping platform. It is completely free to join and list toys.
			 */
			answer5: () => LocalizedString
		}
	}
}

export type Formatters = {}
