// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'pl'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * B​a​s​e
	 */
	base: string
	links: {
		/**
		 * H​o​m​e​p​a​g​e
		 */
		homepage: string
		/**
		 * T​o​y​s
		 */
		toys: string
		/**
		 * A​d​m​i​n​ ​p​a​g​e
		 */
		adminPage: string
		/**
		 * L​o​g​o​u​t
		 */
		logout: string
		/**
		 * L​o​g​i​n
		 */
		login: string
		/**
		 * R​e​g​i​s​t​e​r
		 */
		register: string
	}
}

export type TranslationFunctions = {
	/**
	 * Base
	 */
	base: () => LocalizedString
	links: {
		/**
		 * Homepage
		 */
		homepage: () => LocalizedString
		/**
		 * Toys
		 */
		toys: () => LocalizedString
		/**
		 * Admin page
		 */
		adminPage: () => LocalizedString
		/**
		 * Logout
		 */
		logout: () => LocalizedString
		/**
		 * Login
		 */
		login: () => LocalizedString
		/**
		 * Register
		 */
		register: () => LocalizedString
	}
}

export type Formatters = {}
